#!/bin/bash
NBIO=nbio
NVME_CLI=nvme
NVME_CLI_ORG=/usr/sbin/nvme
IOLOG_PREFIX=iolog-
SMARTLOG_PREFIX=smartlog-
ERRORLOG_PREFIX=errorlog-
IOTRACE_PREFIX=iotrace-
IOENGINE=spdk
#IOENGINE=libaio
#PCI_ADDRESS=0000:02:00.0
PCI_ADDRESS=$FQA_DEVICE
WAIT_TIME=1
PMUTEST_REPEAT=10
POWERCTL_BIN=powerctl
POWERCTL_DEV=/dev/ttyUSB0
POWERCTL_CMD_ON=1
POWERCTL_CMD_OFF=0
SPDK_SETUP=../../setup.sh
NBIO_BG_PID=0
PWRCYC=0
UNSAFE=0

if [[ -z $NBIO_NSID ]]; then
  NSID=1
else
  NSID=$NBIO_NSID
fi
if [ $IOENGINE == "spdk" ]; then
  CONTROLLER="$PCI_ADDRESS"
  export FQA_SPDK=1
else
  CONTROLLER="/dev/nvme0"
  export FQA_SPDK=0
fi
#JOURNAL_DIR=$PWD/$(dirname ${BASH_SOURCE[0]})
#JOURNAL_FILE=$JOURNAL_DIR/nvme0n1.journal
if [[ $FQA_TARGET == "native" ]]; then
  JOURNAL_SHM=$((NSID+830))
  COMPARE=true
else
  COMPARE=false
fi

AE_SAVE_CURSOR="\033[s"
AE_RESTORE_CURSOR="\033[u"
AE_CLEAR_EOL="\033[K"

LIST=0
CLEAN=0
ARG=
GROUP_NO=
LOGDIR=$PWD
CONFIGS=0

# default values
NAMESPACE_BSZ=4096
MDTS=$((32 * NAMESPACE_BSZ))

PASS="\033[32;1mpass\033[0m"
FAIL="\033[31;1mfail\033[0m"

function run_config()
{
  if skip_test; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi
  if [ $CLEAN -eq 1 ]; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi

  TITLE="configuration" print_title
  if [ $LIST -eq 1 ]; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi

  printf "$PASS\n"
  TEST_NO=$((TEST_NO + 1))
}

function group_init()
{
  GROUP_DIR=${PWD##*/}
  GROUP_NO=(${GROUP_DIR//./ }[0])
  ARG=$1

  if [ ! -n "${TEST_NO+1}" ]; then
    TEST_NO=0
    echo "$GROUP_NO. $GROUP_TITLE"
  fi

  if [ -n "${CURDIR+1}" ]; then
      LOGDIR=$CURDIR
  fi

  if [ $# -gt 0 ]; then
    if [ "$1" == "list" ]; then
      LIST=1
      return
    elif [ "$1" == "clean" ]; then
      CLEAN=1
      clean_logs
      return
    fi
  fi

  command -v $NVME_CLI >/dev/null    # check if the nvme-cli is installed
  RET=$?
  if [ $RET -ne 0 ]; then
    echo "nvme-cli is not installed"
    exit $RET
  fi

  if [[ $CONTROLLER == '/dev/nvme*' ]]; then
    if [ ! -b "${CONTROLLER}n${NSID}" ]; then
      echo "namespace '${CONTROLLER}n${NSID}' not found"
      exit 1
    fi
  fi
  NAMESPACE_BSZ=`$NVME_CLI id-ns $CONTROLLER -n $NSID | awk '/in use/ { print $5 }' | awk -F ':' '{ print 2^$2 }'`
  NAMESPACE_SIZE=$((NAMESPACE_BSZ * `$NVME_CLI id-ns $CONTROLLER -n $NSID | awk '/nsze/ { print $3 }'`))
  NAMESPACE_SIZE_GB=$((NAMESPACE_SIZE/1024**3))
  #MDTS=$((`$NVME_CLI id-ctrl $CONTROLLER | awk '/mdts/ { print 2^$3*4096 }'`))
  MDTS=$((128 * 1024))
  if [ $# -ge 1 ]; then
    TEST_TO_RUN=$1
  fi
  LOGDIR="$LOGDIR/log"
  mkdir $LOGDIR &> /dev/null
}

function print_title()
{
  TITLE_STR=`eval "echo -n $TITLE"`
  if [ $LIST -eq 1 ]; then
    printf " %02d. %s\n" $TEST_NO "$TITLE_PREFIX$TITLE_STR"
  else
    printf " %02d. %-70s ... " $TEST_NO "$TITLE_PREFIX$TITLE_STR"
  fi
}

function clean_logs()
{
  rm -rf $PWD/log
}

function run_nbio()
{
  if [ -n "${SUBTEST_NO+1}" ]; then
    LOGSUFFIX="-$SUBTEST_NO"
    SUBTEST_NO=$((SUBTEST_NO + 1))
  fi
  if [[ $MULTI_NS == "1" ]]; then
    IOLOG_FILE="$LOGDIR/$IOLOG_PREFIX$PCI_ADDRESS"_"$TEST_NO$LOGSUFFIX"
    SMARTLOG_FILE="$LOGDIR/$SMARTLOG_PREFIX$PCI_ADDRESS"_"$TEST_NO$LOGSUFFIX"
    ERRORLOG_FILE="$LOGDIR/$ERRORLOG_PREFIX$PCI_ADDRESS"_"$TEST_NO$LOGSUFFIX"
    IOTRACE_FILE="$LOGDIR/$IOTRACE_PREFIX$PCI_ADDRESS"_"$TEST_NO$LOGSUFFIX"
  else
    IOLOG_FILE="$LOGDIR/$IOLOG_PREFIX$PCI_ADDRESS"_ns"$NSID"_"$TEST_NO$LOGSUFFIX"
    SMARTLOG_FILE="$LOGDIR/$SMARTLOG_PREFIX$PCI_ADDRESS"_ns"$NSID"_"$TEST_NO$LOGSUFFIX"
    ERRORLOG_FILE="$LOGDIR/$ERRORLOG_PREFIX$PCI_ADDRESS"_ns"$NSID"_"$TEST_NO$LOGSUFFIX"
    IOTRACE_FILE="$LOGDIR/$IOTRACE_PREFIX$PCI_ADDRESS"_ns"$NSID"_"$TEST_NO$LOGSUFFIX"
  fi
  export IOENGINE=$IOENGINE
  export IOLOG=$IOLOG_FILE
  export SMARTLOG=$SMARTLOG_FILE
  export ERRORLOG=$ERRORLOG_FILE
  export IOTRACE=$IOTRACE_FILE
  export CONTROLLER=$CONTROLLER
  export NSID=$NSID
  export JOURNAL_SHM=$JOURNAL_SHM
  export COMPARE=$COMPARE
  if [[ -z $AMOUNT ]]; then
    export AMOUNT="time:20s"
  fi
  if [[ -z $AMOUNT_SCALE ]]; then
    export AMOUNT_SCALE=1
  fi
  if [[ -z $NBIO_BG ]]; then
    export NBIO_BG=0
  fi

  if [[ $NBIO_BG -eq 1 ]]; then
    $NBIO --display testcase $PARAM_FILE $@ &
    RET=$?
    NBIO_BG_PID=$!
  else
    $NBIO --display testcase $PARAM_FILE $@
    RET=$?
    NBIO_BG_PID=0
  fi
  
  if [ $RET -eq 1 ]; then
    printf "abort\n"
    exit $RET
  elif [ $RET -gt 1 ]; then
    printf "$FAIL\n"
    if [ -s $ERRORLOG_FILE ]; then
      echo "check the log '$ERRORLOG_FILE' for details"
    fi
    exit $RET
  fi
  if [ ! -s $ERRORLOG_FILE ]; then
    # remove empty error log file
    rm -f $ERRORLOG_FILE
  fi
}

function skip_test()
{
  if [ -n "${TEST_TO_RUN+1}" ]; then
    if [ $TEST_TO_RUN -eq $TEST_NO ]; then
      return 1
    fi
    return 0
  fi
  return 1
}

function run_test()
{
  if skip_test; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi
  if [ $CLEAN -eq 1 ]; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi

  print_title
  if [ $LIST -eq 1 ]; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi

  if [ -n "${PRETEST_EVENT+1}" ]; then
    $PRETEST_EVENT
  fi

  run_nbio

  if [ -n "${POSTTEST_EVENT+1}" ]; then
    $POSTTEST_EVENT
  fi

  printf "$PASS\n"
  if [ ! -s $ERRORLOG_FILE ]; then
    # remove empty error log file
    rm -f $ERRORLOG_FILE
  fi
  TEST_NO=$((TEST_NO + 1))
}

log()
{
    now=`date '+%b %d %H:%M:%S'`
    >&2 echo "$now $@"
}

function run_custom()
{
  if skip_test; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi
  if [ $CLEAN -eq 1 ]; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi

  print_title
  if [ $LIST -eq 1 ]; then
    TEST_NO=$((TEST_NO + 1))
    return 0
  fi

  if [ -n "${PRETEST_EVENT+1}" ]; then
    $PRETEST_EVENT
  fi

  TESTLOG_FILE=$LOGDIR/testlog-$TEST_NO
  SUBTEST_NO=1
  print_title > $TESTLOG_FILE
  $@ 2>> $TESTLOG_FILE

  RET=$?
  if [ $RET -ne 0 ]; then
    printf "$FAIL\n"
    if [ -s $ERRORLOG_FILE ]; then
      echo "check the log '$ERRORLOG_FILE' for details"
    fi
    exit $RET
  fi

  if [ -n "${POSTTEST_EVENT+1}" ]; then
    $POSTTEST_EVENT
  fi

  printf "$PASS\n"
  if [ ! -s $ERRORLOG_FILE ]; then
    # remove empty error log file
    rm -f $ERRORLOG_FILE
  fi
  TEST_NO=$((TEST_NO + 1))
}

function run_groups()
{
  CURDIR=$PWD
  for group in "$@"
  do
    cd $CURDIR
    cd $1
    x()
    {
      source run $ARG
    }
    x
  done
  cd $CURDIR
}

function clean_journal()
{
  #rm -f $JOURNAL_FILE
  ipcrm -M $JOURNAL_SHM &> /dev/null
}

function format_512b()
{
  command -v $NVME_CLI >/dev/null    # check if the nvme-cli is installed
  RET=$?
  if [ $RET -ne 0 ]; then
    echo "nvme-cli is not installed"
    exit $RET
  fi

  echo "format 512b"
  $NVME_CLI format $FQA_DEVICE -n $NSID --lbaf=0 >/dev/null
  RET=$?
  if [ $RET -ne 0 ]; then
    echo "namespace format failure"
    exit $RET
  fi
  clean_journal
}

function format_4k()
{
  command -v $NVME_CLI >/dev/null    # check if the nvme-cli is installed
  RET=$?
  if [ $RET -ne 0 ]; then
    echo "nvme-cli is not installed"
    exit $RET
  fi

  echo "format 4k"
  $NVME_CLI format $FQA_DEVICE -n $NSID --lbaf=2 >/dev/null	# FADU
  #$NVME_CLI format $FQA_DEVICE -n $NSID --lbaf=1 >/dev/null	# Intel
  RET=$?
  if [ $RET -ne 0 ]; then
    echo "namespace format failure"
    exit $RET
  fi
  clean_journal
}

function shutdown_device()
{
  sync
  echo "Unloads NVMe device driver"
  rmmod nvme

  return 0
}

function initialize_device()
{
  modprobe nvme retry_time=0

  for ((sec=1; sec<=20; sec++))
  do
    if [ -b $NAMESPACE ]; then
      return 0
    fi
    sleep 1
  done

  echo "namespace '$NAMESPACE' not found"
  exit 1
}

function get_power_cycles_count()
{
	#$NVME_CLI smart-log $FQA_DEVICE | grep "power_cycles"
  PWRCYC=$($NVME_CLI smart-log $FQA_DEVICE --namespace-id $NSID -o json | jq ".power_cycles")
  echo $PWRCYC
}

function get_unsafe_shutdowns_count()
{
	#$NVME_CLI smart-log $FQA_DEVICE | grep "unsafe_shutdowns"
  UNSAFE=$($NVME_CLI smart-log $FQA_DEVICE --namespace-id $NSID -o json | jq ".unsafe_shutdowns")
  echo $UNSAFE
}

function wait_ns_ready_spdk()
{
  RET=1
  while [ $RET -ne 0 ]
  do
    echo "wait ns ready for spdk"
    sleep 1s

    $NVME_CLI read --namespace-id $NSID $FQA_DEVICE -z $LBASIZE > /dev/null
    RET=$?
  done
}

function wait_ns_ready_nvme()
{
  while [ ! -e "/dev/nvme0n$NSID" ]
  do
    echo "/dev/nvme0n$NSID file not ready"
    sleep 1s
  done

  RET=1
  while [ $RET -ne 0 ]
  do
    echo "wait ns ready for nvme"
    sleep 1s
    $NVME_CLI_ORG read /dev/nvme0n$NSID -z $LBASIZE > /dev/null
    RET=$?
  done
}

function pci_type_check()
{
  return
  PCI_TYPE=`lspci | grep $PCI_ADDRESS | grep 1dc5:6150 | awk '{print $2}'`
  if [ "$PCI_TYPE" = "Non-Volatile" ] ; then
    echo "OK"
  else
    echo "PCIe Scan Failed: Wrong device type ($PCI_TYPE)"
    exit -1
  fi
}

function pci_rescan()
{
  # re-enumerate pci bus
  RESCAN_SUCCESS=0
  RESCAN_RETRY_COUNT=0
  MAX_RESCAN_RETRY_COUNT=5
  #RESCAN_WAIT_TIME=1s
  RESCAN_WAIT_TIME=0.1s

  while [ $RESCAN_SUCCESS -ne 1 ]
  do
    echo "1" > /sys/bus/pci/rescan
    sleep $RESCAN_WAIT_TIME

    if [ -d /sys/bus/pci/devices/$PCI_ADDRESS ]; then
      echo "RESCAN success"
      RESCAN_SUCCESS=1
    else
      if [ $RESCAN_RETRY_COUNT -eq $MAX_RESCAN_RETRY_COUNT ]; then
        printf "$FAIL - PCIe Scan Failed\n"
        exit -1
      fi

      RESCAN_RETRY_COUNT=$((RESCAN_RETRY_COUNT+1))
      echo "RESCAN failed, retry count: $RESCAN_RETRY_COUNT"
    fi
  done
}

function power_on_for_if()
{
  echo "pwr $PORT $POWERCTL_CMD_ON"
  pwr $PORT $POWERCTL_CMD_ON
}

function power_off_for_if()
{
  echo "pwr $PORT $POWERCTL_CMD_OFF"
  pwr $PORT $POWERCTL_CMD_OFF
}

function power_on()
{
  # power on
  #echo "$POWERCTL_BIN $POWERCTL_DEV $POWERCTL_CMD_ON > /dev/null"
  echo "Sends PCIe power on command to power control device"
  # $POWERCTL_BIN ${POWERCTL_DEV} $POWERCTL_CMD_ON > /dev/null
  power_on_for_if

  pci_rescan
  pci_type_check

  # wait_ns_ready_nvme

  return 0
}

function spo_at_spor()
{
	if [ $SPO_AT_SPOR_RATIO -eq 0 ]; then
	sleep 40
    return
  fi
  
	if [ $(( ( RANDOM % SPO_AT_SPOR_RATIO )  + 1 )) -eq 1 ]; then
		echo "Sends PCIe power on command to power control device"
		# $POWERCTL_BIN ${POWERCTL_DEV} $POWERCTL_CMD_ON > /dev/null
    power_on_for_if
		
#		pci_rescan
#		pci_type_check

	  SPO_AT_SPOR_TIME=$(( ( RANDOM % (SPO_AT_SPOR_MSEC_MAX - SPO_AT_SPOR_MSEC_MIN) ) + SPO_AT_SPOR_MSEC_MIN ))
		SPO_AT_SPOR_TIME=$(echo "scale=3; $SPO_AT_SPOR_TIME/1000" | bc)

		echo "**********************************"
		echo "[$SPO_AT_SPOR_CNT] SPO at SPOR (after $SPO_AT_SPOR_TIME s : $SPO_AT_SPOR_MSEC_MIN ~ $SPO_AT_SPOR_MSEC_MAX ms)"
		echo "**********************************"

		sleep $SPO_AT_SPOR_TIME

		echo "Sends PCIe power off command to power control device"
		# $POWERCTL_BIN ${POWERCTL_DEV} $POWERCTL_CMD_OFF > /dev/null
    power_off_for_if

#    echo "Waiting for $WAIT_TIME seconds"
#    sleep $WAIT_TIME

#    # remove the knowledge of the device
#    echo "Removes $PCI_ADDRESS device"
#    echo "1" > /sys/bus/pci/devices/$PCI_ADDRESS/remove 

		echo "wait 3s"
		sleep 40 #3->30

		SPO_AT_SPOR_CNT=$((SPO_AT_SPOR_CNT + 1))
	fi
}

function spo_at_npo()
{
  if [ $NBIO_BG_PID -ne 0 ]; then
    echo "kill nbio $NBIO_BG_PID after $WAIT_TIME sec"
    sleep $WAIT_TIME
    kill -SIGINT $NBIO_BG_PID

    #echo "wait for killing nbio $NBIO_BG_PID"
    #wait $NBIO_BG_PID

    #echo "killed $NBIO_BG_PID"
    #NBIO_BG_PID=0

    #$NVME_CLI read $FQA_DEVICE --namespace-id $NSID -z $LBASIZE & > /dev/null
  fi

	if [ $SPO_AT_NPO_RATIO -eq 0 ]; then
    NBIO_BG_PID=0
    return
  fi

	if [ $(( ( RANDOM % SPO_AT_NPO_RATIO )  + 1 )) -eq 1 ]; then
    SPO_AT_NPO_TIME=$(( ( RANDOM % (SPO_AT_NPO_MSEC_MAX - SPO_AT_NPO_MSEC_MIN) ) + SPO_AT_NPO_MSEC_MIN ))
    SPO_AT_NPO_TIME=$(echo "scale=3; $SPO_AT_NPO_TIME/1000" | bc)

    echo "SPO at NPO (after $SPO_AT_NPO_TIME s : $SPO_AT_NPO_MSEC_MIN ~ $SPO_AT_NPO_MSEC_MAX ms)"
    sleep $SPO_AT_NPO_TIME
  else
    echo "wait for killing nbio $NBIO_BG_PID (skip SPO at NPO)"
    wait $NBIO_BG_PID
  fi

  NBIO_BG_PID=0

  # power off
  #echo "$POWERCTL_BIN $POWERCTL_DEV $POWERCTL_CMD_OFF > /dev/null"
  echo "Sends PCIe power off command to power control device"

  # $POWERCTL_BIN ${POWERCTL_DEV} $POWERCTL_CMD_OFF > /dev/null
  power_off_for_if
  RET=$?
	
  if [ $RET -ne 0 ]; then
	echo "Power off failed. Command line is"
  	# echo "$POWERCTL_BIN ${POWERCTL_DEV} $POWERCTL_CMD_OFF > /dev/null"
    power_off_for_if
	exit $RET
  fi

  echo "Waiting for $WAIT_TIME seconds"
  sleep $WAIT_TIME

  # remove the knowledge of the device
  echo "Removes $PCI_ADDRESS device"
  echo "1" > /sys/bus/pci/devices/$PCI_ADDRESS/remove
  #echo "Waiting for $WAIT_TIME seconds"
  sleep $WAIT_TIME

  # re-enumerate pci bus
  echo "Re-enumerates pci bus"
  echo "1" > /sys/bus/pci/rescan
  #echo "Waiting for $WAIT_TIME seconds"
  sleep $WAIT_TIME

  return 0
}

function power_off()
{
  # power off
  #echo "$POWERCTL_BIN $POWERCTL_DEV $POWERCTL_CMD_OFF > /dev/null"
  echo "Sends PCIe power off command to power control device"

  # $POWERCTL_BIN ${POWERCTL_DEV} $POWERCTL_CMD_OFF > /dev/null
  power_off_for_if
  RET=$?
	
  if [ $RET -ne 0 ]; then
	echo "Power off failed. Command line is"
  	# echo "$POWERCTL_BIN ${POWERCTL_DEV} $POWERCTL_CMD_OFF > /dev/null"
    power_off_for_if
	exit $RET
  fi

  if [ $NBIO_BG_PID -ne 0 ]; then
    echo "kill nbio $NBIO_BG_PID after $WAIT_TIME sec"
    sleep $WAIT_TIME
    kill -SIGUSR1 $NBIO_BG_PID

    sleep 3
    echo "wait for killing nbio $NBIO_BG_PID"
    wait $NBIO_BG_PID

    echo "killed $NBIO_BG_PID"
    NBIO_BG_PID=0
  fi

  echo "Waiting for $WAIT_TIME seconds"
  sleep 30 #10->30
  #sleep $WAIT_TIME

  # remove the knowledge of the device
  echo "Removes $PCI_ADDRESS device"
  echo "1" > /sys/bus/pci/devices/$PCI_ADDRESS/remove
  #echo "Waiting for $WAIT_TIME seconds"
  sleep $WAIT_TIME

  # re-enumerate pci bus
  echo "Re-enumerates pci bus"
  echo "1" > /sys/bus/pci/rescan
  #echo "Waiting for $WAIT_TIME seconds"
  sleep $WAIT_TIME

  return 0
}

function power_off_post_process()
{
  echo "Waiting for $WAIT_TIME seconds"
  sleep $WAIT_TIME

  # remove the knowledge of the device
  echo "Removes $PCI_ADDRESS device"
  echo "1" > /sys/bus/pci/devices/$PCI_ADDRESS/remove
  echo "Waiting for $WAIT_TIME seconds"
  sleep $WAIT_TIME

  # re-enumerate pci bus
  echo "Re-enumerates pci bus"
  echo "1" > /sys/bus/pci/rescan
  echo "Waiting for $WAIT_TIME seconds"
  sleep $WAIT_TIME

  return 0
}

function reset_spdk()
{
	echo "Reset spdk"
	PCI_WHITELIST="${PCI_ADDRESS}" $SPDK_SETUP reset
}

function enable_spdk()
{
  while [ true ]
  do
    echo "Enabling spdk..."
    PCI_WHITELIST="${PCI_ADDRESS}" $SPDK_SETUP

    SPDK_DRIVER=`$SPDK_SETUP status | grep $PCI_ADDRESS | awk '/uio/ { print $3 }'`
    if [ "$SPDK_DRIVER" = "uio_pci_generic" ]; then
      echo "Enabling spdk succeed."
      wait_ns_ready_spdk
      return
    else
      echo "Enabling spdk failed. Try again..."
      power_off
      reset_spdk
      power_on
    fi
  done
}

function pmutest()
{
  echo "PMU-mainboard compatiblity test"

  for (( i = 1 ; i <= $PMUTEST_REPEAT ; i++))
  do
	echo "PMU test loop $i"
	shutdown_device
    power_off
    power_on
    initialize_device
    get_power_cycles_count

  done

  return 0
}


function register_config()
{
  CONFIG_NAME[CONFIGS]=$1
  CONFIG_FUNC[CONFIGS]=$2
  CONFIGS=$((CONFIGS+1))
}

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT

function ctrl_c() {
  echo -e "\n\n\n*** Trapped CTRL-C ***"

  if [ $NBIO_BG_PID -ne 0 ]; then
    echo "kill nbio $NBIO_BG_PID"
    sleep 1
    kill -SIGUSR1 $NBIO_BG_PID
    NBIO_BG_PID=0
  fi

  exit -1
}
