#!/bin/bash
DEV=$FQA_DEVICE

killall prim_proc
../tools/prim_proc/prim_proc&
sleep 1

nvme delete-ns $DEV -n 0xffffffff								# delete all namespaces

./run clean > /dev/null

CTRL_ID=$(nvme id-ctrl $DEV | grep cntlid | awk '{print $3}')

nsbytes=`nvme id-ctrl $DEV | grep tnvmcap | awk 'BEGIN {OFMT="%.0f"} {GB=1024*1024*1024;ns_size=(int($3/GB)*GB);print ns_size;}'`
lba4k_nscap=`awk 'BEGIN {OFMT="%.0f"; print '$nsbytes'/4096}'`
lba512b_nscap=`awk 'BEGIN {OFMT="%.0f"; print '$nsbytes'/512}'`

nvme create-ns $DEV -s $lba4k_nscap   -c $lba4k_nscap   -f 2 -m 1		# nsid 1.  4kb
#nvme create-ns $DEV -s $lba512b_nscap -c $lba512b_nscap -f 0 -m 1		# nsid 2.  512b

nvme attach-ns $DEV -n 1 -c $CTRL_ID

killall prim_proc
