#!/bin/bash
source common
#source configs/3200GB
#source configs/2850GB
#source configs/400GB_precond
GROUP_NO=1

function skip_group()
{
  if [ ! -z ${GROUP_TO_RUN+x} ]; then
    if [ $GROUP_TO_RUN -ne $GROUP_NO ]; then
      return 0
    fi
    return 1
  fi
  return 1
}

function run_group()
{
  GROUP_NO=(${1//./ }[0])
  if skip_group; then
    return 0
  fi

  if [ ! -d $1 ]; then
    echo "test group '$1' not found"
    exit 1
  fi
  cd $1
  GROUP_NO=$GROUP_NO ./run $GROUP_ARG
  if [ $? -ne 0 ]; then
    exit $?
  fi
  cd ..
}

function help()
{
  echo "block-level testing tool v0.7"
  echo "usage: $0 [options | [test group | [test case]]]"
  echo "option:   help    shows this screen"
  echo "          list    lists available test cases"
  echo "          clean   removes journal and test logs"
  echo "          pmutest verifies pmu and mainboard compatibility"
}

if [ $# -gt 0 ]; then
  if [ "$1" == "help" ]; then
    help
    exit
  elif [ "$1" == "list" ]; then
    GROUP_ARG=list
  elif [ "$1" == "clean" ]; then
    GROUP_ARG=clean
    clean_journal
	exit
  elif [ "$1" == "pmutest" ]; then
	pmutest
	RET=$?
    if [ $RET -eq 0 ]; then
      echo "pmutest completed successfully"
    else
      echo "pmutest failed"
    fi
    exit $RET
  else
    if ! [[ $1 =~ ^[0-9]+$ ]]; then
      echo "not a number $1"
      help
      exit
    fi
    GROUP_TO_RUN=$1
    if [ $# -gt 1 ]; then
      GROUP_ARG=$2
    fi
  fi
fi

run_group "1.spor_wo_write"
run_group "2.spor_w_write"

