#!/bin/bash
source ../common
GROUP_TITLE="single operation test(8 namespaces without 512B)"
PARAM_FILE=parameter_ns8
TITLE='OPERATION=$OPERATION IOSIZE=4KB_LBA:$IOSIZE_4KB'
SEED=1
MULTI_NS=1

if [[ -n $STATIC_AMOUNT ]]; then
	export AMOUT=$STATIC_AMOUNT
fi

group_init $@

run_config
IOSIZE_4KB=4096
for ((IOSIZE_4KB=4096;IOSIZE_4KB<=MDTS;IOSIZE_4KB*=2))
do
  AMOUNT_SCALE=1 OPERATION="write" IOSIZE_4KB="$IOSIZE_4KB" SEED="$SEED" run_test
  AMOUNT_SCALE=1 OPERATION="read" IOSIZE_4KB="$IOSIZE_4KB"  SEED="$SEED" run_test
  SEED=$((SEED+1))
done

