#!/bin/bash

source ./vu_tools.sh

DEV_NAME=/dev/nvme0n1
NSID=1
VU_SUB_OPCODE=0x00000100 #VU_WRITE_EXAMPLE
DATA_LEN_BYTE=12
PARAM0=0xAA
PARAM1=0XBB
PARAM2=0XCC
PARAM3=0XDD

vu_write_common $DEV_NAME $NSID $VU_SUB_OPCODE $DATA_LEN_BYTE $PARAM0 $PARAM1 $PARAM2 $PARAM3

