# initialize
./initialize
delete-ns: Success, deleted nsid:-1
allocated nvm capacitiy is 0GB(0B)

# private namespace
nvme create-ns $FQA_DEVICE -s 0x1000 -c 0x1000 -f 0 -d 0 -m 0
create-ns: Success, created nsid:1
nvme id-ns $FQA_DEVICE -n 1 | grep nmic
nmic    : 0

# shared namespace
nvme create-ns $FQA_DEVICE -s 0x1000 -c 0x1000 -f 0 -d 0 -m 1
create-ns: Success, created nsid:2
nvme id-ns $FQA_DEVICE -n 2 -f | grep nmic
nmic    : 0x1
