#!/bin/bash
RELEASE=`cat /etc/centos-release`
KERNEL=`uname -r`
echo "h1. Summary"
echo "h2. Test Environment"
echo "h2. Device Uner Test"
echo "h2. Test System"
echo "* Test P #7, [06_Test Equipments]"
echo "* $RELEASE, kernel $KERNEL"
echo "h2. Testing Tool"
echo "* NVMe Block I/O"
echo "h3. Test Result"
echo "h2. Single Operation Test"
cd 1.single;./report;cd ../
echo "h2. Multiple Operation Test"
cd 2.multiple;./report;cd ../
echo "h2. Mixed Operation Test"
cd 3.mixed;./report;cd ../
echo "h2. Multi-thread Mixed Operation Test"
cd 4.mt_mixed;./report;cd ../
echo "h2. Write & Read Dependency Test"
echo "h2. Format Test"
echo "h2. Hot-spot Read Test"
echo "h2. Close & Read Test"
echo "h2. Wholespace Access Test"
