#!/bin/bash
source ../common
GROUP_TITLE="single operation sequential test"
PARAM_FILE=parameter
TITLE='OPERATION=$OPERATION SLBA=$SLBA IOSIZE=$IOSIZE'
SEED=1
START=0
NLBS=16

group_init $@

run_config
if [[ $NAMESPACE_BSZ == 4096 ]]; then
  # 4KB LBA
  for ((IOSIZE=NAMESPACE_BSZ;IOSIZE<=MDTS;IOSIZE+=NAMESPACE_BSZ))
  do
    LAST=$((START+NLBS))
    for ((SLBA=START;SLBA<LAST;SLBA+=1))
    do
       OPERATION=write SLBA=fixed:$SLBA IOSIZE=$IOSIZE SEED=$SEED run_test
       OPERATION=read SLBA=fixed:$SLBA IOSIZE=$IOSIZE SEED=$SEED run_test
    done

    START=$((START+NLBS))
    SEED=$((SEED+1))
  done
else
  # 512B LBA
  for ((IOSIZE=NAMESPACE_BSZ;IOSIZE<4096;IOSIZE+=NAMESPACE_BSZ))
  do
    LAST=$((START+NLBS))
    for ((SLBA=START;SLBA<LAST;SLBA+=1))
    do
       OPERATION=write SLBA=fixed:$SLBA IOSIZE=$IOSIZE SEED=$SEED run_test
       OPERATION=read SLBA=fixed:$SLBA IOSIZE=$IOSIZE SEED=$SEED run_test
    done

    START=$((START+NLBS))
    SEED=$((SEED+1))
  done
  for ((IOSIZE=4096;IOSIZE<=MDTS;IOSIZE*=2))
  do
    LAST=$((START+NLBS))
    for ((SLBA=START;SLBA<LAST;SLBA+=1))
    do
       OPERATION=write SLBA=fixed:$SLBA IOSIZE=$IOSIZE SEED=$SEED run_test
       OPERATION=read SLBA=fixed:$SLBA IOSIZE=$IOSIZE SEED=$SEED run_test
    done

    START=$((START+NLBS))
    SEED=$((SEED+1))
  done

fi
