#!/usr/bin/env bash
source ../common > /dev/null 2>&1

make > /dev/null

FQA_SPDK=1
../../setup config 2&> /dev/null
rescan-ns

nvme delete-ns $FQA_DEVICE -n 0xFFFFFFFF
nvme create-ns $FQA_DEVICE -s 0x10000 -c 0x10000 -f 0
nvme attach-ns $FQA_DEVICE -n 1 -c $CTRL_ID

rescan-ns

nvme format $FQA_DEVICE -n 1

nvme set-feature $FQA_DEVICE -f 0xa -v 0    # enable atomic write
nvme get-feature $FQA_DEVICE -f 0xa         # check

./atomic_write > /dev/null
res=$?
if [[ $res == 0 ]]; then
  echo "no data mix found"
else
  echo "data mix found despite atomic write enabled"
fi

nvme delete-ns $FQA_DEVICE -n 0xFFFFFFFF
nvme create-ns $FQA_DEVICE -s 0x10000 -c 0x10000 -f 2
nvme attach-ns $FQA_DEVICE -n 1 -c $CTRL_ID

rescan-ns

nvme set-feature $FQA_DEVICE -f 0xa -v 0    # enable atomic write
nvme get-feature $FQA_DEVICE -f 0xa         # check

./atomic_write > /dev/null
res=$?
if [[ $res == 0 ]]; then
  echo "no data mix found"
else
  echo "data mix found despite atomic write enabled"
fi

nvme set-feature $FQA_DEVICE -f 0xa -v 1    # disable atomic write
