#!/bin/bash
# analyze test log and print summary formatted with confluence markup

TEST_NO=1
LOGDIR="$PWD/log"

function analyze_log()
{
  IOLOG="$LOGDIR/iolog-$TEST_NO"
  ERRORLOG="$LOGDIR/errorlog-$TEST_NO"
  SMARTLOG="$LOGDIR/smartlog-$TEST_NO"
  TEST_NO=$((TEST_NO+1))
  if [ ! -f $IOLOG ]; then
    return
  fi
  if [ ! -f $ERRORLOG ]; then
    RESULT="*{color:blue}Pass{color}*"
  else
    RESULT="*{color:red}Fail{color}*"
  fi
  printf "|%s|%s|%s|%s|" "$1" "$2" "$3" "$RESULT"
  if [ $1 == "Read" ]; then
    tail -n 1 $IOLOG | sed -r 's/^.{2}//' | awk -F',' '{time=$1; throughput=$2; iops=$3; latency_ns=$4} END { printf("%'"'"'g|%'"'"'u|%'"'"'u|%'"'"'u|\n",time,throughput/1024/1024,iops,latency_ns/1000) }'
  else
    tail -n 1 $IOLOG | sed -r 's/^.{2}//' | awk -F',' '{time=$1; throughput=$5; iops=$6; latency_ns=$7} END { printf("%'"'"'g|%'"'"'u|%'"'"'u|%'"'"'u|\n",time,throughput/1024/1024,iops,latency_ns/1000) }'
  fi
}

if [ -z "$LOGDIR" ]; then
  echo "no test log found"
  exit 0
else
  echo "test log: $LOGDIR"
fi

echo "||I/O Operation||I/O Size||I/O Depth||Result||Elapsed Time\\\\(sec)||Throughput\\\\(MB/s)||IOPs||Latency\\\\(us)||"

analyze_log "Write" "4KB" "32"
analyze_log "Read" "4KB" "32"
analyze_log "Write" "4KB" "128"
analyze_log "Read" "4KB" "128"
analyze_log "Write" "4KB" "512"
analyze_log "Read" "4KB" "512"
analyze_log "Write" "4KB" "2048"
analyze_log "Read" "4KB" "2048"
analyze_log "Write" "1020KB" "32"
analyze_log "Read" "1020KB" "32"
analyze_log "Write" "1020KB" "128"
analyze_log "Read" "1020KB" "128"
analyze_log "Write" "1020KB" "512"
analyze_log "Read" "1020KB" "512"
analyze_log "Write" "1020KB" "2048"
analyze_log "Read" "1020KB" "2048"

